import Poincare.TetrahedronSphere

open Set

namespace Poincare

/-- The ambient Euclidean four-space used for the standard geometric 4-simplex. -/
abbrev FourSimplexAmbient := EuclideanSpace ℝ (Fin 4)

/-- A chosen affine basis of Euclidean four-space, indexed by five vertices. -/
noncomputable def fourSimplexAffineBasis :
    AffineBasis (Fin 5) ℝ FourSimplexAmbient := by
  exact Classical.choice
    (AffineBasis.exists_affineBasis_of_finiteDimensional
      (ι := Fin 5) (k := ℝ) (V := FourSimplexAmbient)
      (P := FourSimplexAmbient) (by simp))

/-- The four-dimensional simplex determined by `fourSimplexAffineBasis`. -/
noncomputable def fourSimplex :
    Affine.Simplex ℝ FourSimplexAmbient 4 where
  points := fourSimplexAffineBasis
  independent := fourSimplexAffineBasis.ind

/-- The closed convex body generated by the five affine-basis points. -/
noncomputable def fourSimplexBody : Set FourSimplexAmbient :=
  convexHull ℝ (Set.range fourSimplexAffineBasis)

theorem fourSimplexBody_convex : Convex ℝ fourSimplexBody := by
  exact convex_convexHull ℝ _

theorem fourSimplexAffineBasis_full_span :
    affineSpan ℝ (Set.range fourSimplexAffineBasis) = ⊤ := by
  exact fourSimplexAffineBasis.tot

theorem fourSimplexBody_interior_nonempty :
    (interior fourSimplexBody).Nonempty := by
  refine ⟨Finset.univ.centroid ℝ fourSimplexAffineBasis, ?_⟩
  simpa [fourSimplexBody] using
    fourSimplexAffineBasis.centroid_mem_interior_convexHull

theorem fourSimplexBody_isCompact : IsCompact fourSimplexBody := by
  simpa [fourSimplexBody] using
    (Set.finite_range fourSimplexAffineBasis).isCompact_convexHull ℝ

theorem fourSimplexBody_isBounded :
    Bornology.IsBounded fourSimplexBody := by
  exact fourSimplexBody_isCompact.isBounded

/-- The frontier of the standard 4-simplex is homeomorphic to the unit 3-sphere. -/
noncomputable def fourSimplexFrontierHomeomorphUnitSphere :
    ↥(frontier fourSimplexBody) ≃ₜ
      ↥(Metric.sphere (0 : FourSimplexAmbient) 1) := by
  let hex : ∃ h : FourSimplexAmbient ≃ₜ FourSimplexAmbient,
      h '' interior fourSimplexBody = Metric.ball 0 1 ∧
      h '' closure fourSimplexBody = Metric.closedBall 0 1 ∧
      h '' frontier fourSimplexBody = Metric.sphere 0 1 :=
    exists_homeomorph_image_interior_closure_frontier_eq_unitBall
      fourSimplexBody_convex fourSimplexBody_interior_nonempty
      fourSimplexBody_isBounded
  let h : FourSimplexAmbient ≃ₜ FourSimplexAmbient := Classical.choose hex
  have hspec :
      h '' interior fourSimplexBody = Metric.ball 0 1 ∧
      h '' closure fourSimplexBody = Metric.closedBall 0 1 ∧
      h '' frontier fourSimplexBody = Metric.sphere 0 1 :=
    Classical.choose_spec hex
  exact (h.image (frontier fourSimplexBody)).trans
    (Homeomorph.setCongr hspec.2.2)

theorem fourSimplex_points_eq_affineBasis :
    fourSimplex.points = fourSimplexAffineBasis := by
  rfl

/-- The face opposite `i` contains precisely the other four vertices. -/
theorem fourSimplexFaceOpposite_vertexSet_eq_image_erase (i : Fin 5) :
    Set.range (fourSimplex.faceOpposite i).points =
      fourSimplex.points '' (↑(Finset.univ.erase i) : Set (Fin 5)) := by
  rw [Affine.Simplex.range_faceOpposite_points]
  congr 1
  ext j
  simp

/-- The union of the five filled facets opposite the five vertices. -/
noncomputable def fourSimplexFacetUnion : Set FourSimplexAmbient :=
  {p | ∃ i : Fin 5,
    p ∈ convexHull ℝ (Set.range (fourSimplex.faceOpposite i).points)}

/-- The frontier is exactly the union of the five opposite-vertex facets. -/
theorem fourSimplexFrontier_eq_facetUnion :
    frontier fourSimplexBody = fourSimplexFacetUnion := by
  rw [fourSimplexBody_isCompact.isClosed.frontier_eq]
  ext p
  rw [mem_diff, fourSimplexFacetUnion, mem_setOf_eq]
  rw [fourSimplexBody, fourSimplexAffineBasis.interior_convexHull,
    fourSimplexAffineBasis.convexHull_eq_nonneg_coord]
  constructor
  · rintro ⟨hpnonneg, hpnotpos⟩
    change ¬ ∀ i, 0 < fourSimplexAffineBasis.coord i p at hpnotpos
    rw [not_forall] at hpnotpos
    simp only [not_lt] at hpnotpos
    obtain ⟨i, hi⟩ := hpnotpos
    have hizero : fourSimplexAffineBasis.coord i p = 0 :=
      le_antisymm hi (hpnonneg i)
    refine ⟨i, ?_⟩
    let w : Fin 5 → ℝ := fun j => fourSimplexAffineBasis.coord j p
    have hsum : ∑ j, w j = 1 :=
      fourSimplexAffineBasis.sum_coord_apply_eq_one p
    have hsum_erase : ∑ j ∈ Finset.univ.erase i, w j = 1 := by
      rw [Finset.sum_erase]
      · simp [w] at hsum ⊢
      · exact hizero
    have hface : ∀ j ∈ Finset.univ.erase i,
        fourSimplex.points j ∈
          Set.range (fourSimplex.faceOpposite i).points := by
      intro j hj
      rw [Affine.Simplex.range_faceOpposite_points]
      exact ⟨j, by simpa using hj, rfl⟩
    have hmem := Finset.centerMass_mem_convexHull
      (s := Set.range (fourSimplex.faceOpposite i).points)
      (z := fourSimplex.points) (Finset.univ.erase i)
      (fun j _ => hpnonneg j) (hsum_erase.symm ▸ zero_lt_one) hface
    rw [← affineCombination_eq_centerMass hsum_erase] at hmem
    have heq : (Finset.univ.erase i).affineCombination ℝ
        fourSimplex.points w = p := by
      rw [Finset.affineCombination_eq_weightedVSubOfPoint_vadd_of_sum_eq_one
        (Finset.univ.erase i) w fourSimplex.points hsum_erase
        (fourSimplex.points i)]
      rw [← fourSimplexAffineBasis.affineCombination_coord_eq_self p]
      simp only [fourSimplex_points_eq_affineBasis]
      rw [Finset.affineCombination_eq_weightedVSubOfPoint_vadd_of_sum_eq_one
        Finset.univ w fourSimplexAffineBasis hsum
        (fourSimplexAffineBasis i)]
      simp [w]
    rwa [heq] at hmem
  · rintro ⟨i, hpface⟩
    have hsubset :
        convexHull ℝ (Set.range (fourSimplex.faceOpposite i).points) ⊆
          convexHull ℝ (Set.range fourSimplexAffineBasis) := by
      apply convexHull_mono
      rw [Affine.Simplex.range_faceOpposite_points,
        fourSimplex_points_eq_affineBasis]
      exact Set.image_subset_range _ _
    have hpbodymem : p ∈ convexHull ℝ (Set.range fourSimplexAffineBasis) :=
      hsubset hpface
    have hpbody : ∀ j, 0 ≤ fourSimplexAffineBasis.coord j p := by
      rwa [fourSimplexAffineBasis.convexHull_eq_nonneg_coord] at hpbodymem
    refine ⟨hpbody, ?_⟩
    intro hpinterior
    have hpaff : p ∈ affineSpan ℝ
        (Set.range (fourSimplex.faceOpposite i).points) :=
      (convexHull_min (subset_affineSpan ℝ _) (affineSpan ℝ _).convex) hpface
    have hsum := fourSimplexAffineBasis.sum_coord_apply_eq_one p
    have hizero : fourSimplexAffineBasis.coord i p = 0 := by
      have h := (Affine.Simplex.affineCombination_mem_affineSpan_faceOpposite_iff
        (s := fourSimplex) (i := i) hsum).mp (by
          simpa [fourSimplex_points_eq_affineBasis,
            fourSimplexAffineBasis.affineCombination_coord_eq_self p] using hpaff)
      simpa [fourSimplex_points_eq_affineBasis] using h
    have hipos := hpinterior i
    rw [hizero] at hipos
    exact (lt_irrefl 0) hipos

end Poincare
