import Poincare.FourSimplexBoundaryCombinatorialCertificate
import Poincare.TriangulationPreAbstractComplex

namespace Poincare

set_option maxHeartbeats 1000000 in
/-- Under the zero-defect and overlap-connected hypotheses, the faces generated by the
tetrahedra are exactly the nonempty proper subsets of the five vertices in the
four-simplex-boundary certificate. -/
theorem ClosedTriangulationCore.triangulationPreAbstractComplex_mem_iff_fourSimplexBoundary
    {K : Triangulation}
    (hcore : ClosedTriangulationCore K)
    (hPhi : PhiSupport K = 0)
    (hconn : TetrahedronVertexOverlapConnected K)
    {τ : Tet}
    (hτK : τ ∈ K.tets)
    (hτ : τ.verts.Nodup) :
    ∃ e,
      [τ.v0, τ.v1, τ.v2, τ.v3, e].Nodup ∧
      ∀ F : Finset Nat,
        F ∈ triangulationPreAbstractComplex K ↔
          F.Nonempty ∧
          F ⊆ {τ.v0, τ.v1, τ.v2, τ.v3, e} ∧
          F ≠ {τ.v0, τ.v1, τ.v2, τ.v3, e} := by
  obtain ⟨ρ012, ρ013, ρ023, ρ123, e,
    h012K, h013K, h023K, h123K, _heτ, hdistinct,
    _hsupport, _hsupportFinset, _htetsFinset,
    hτFinset, h012Finset, h013Finset, h023Finset, h123Finset, hglobal⟩ :=
      hcore.exists_fourSimplexBoundary_combinatorial_certificate hPhi hconn hτK hτ
  refine ⟨e, hdistinct, fun F => ?_⟩
  let V : Finset Nat := {τ.v0, τ.v1, τ.v2, τ.v3, e}
  have hdistinct' := hdistinct
  simp only [List.nodup_cons, List.mem_cons, List.mem_singleton, not_or,
    List.nodup_nil] at hdistinct'
  constructor
  · intro hF
    obtain ⟨hFnonempty, σ, hσK, hFσ⟩ :=
      (mem_triangulationPreAbstractComplex_iff K F).mp hF
    refine ⟨hFnonempty, ?_, ?_⟩
    · rcases hglobal σ hσK with hσ | hσ | hσ | hσ | hσ
      all_goals rw [hσ] at hFσ
      all_goals intro y hy
      all_goals have := hFσ hy
      all_goals simp [V] at this ⊢
      all_goals aesop
    · intro hFVeq
      have hVσ : V ⊆ σ.verts.toFinset := by
        intro y hy
        apply hFσ
        rw [hFVeq]
        simpa [V] using hy
      have hVcard : V.card = 5 := by
        rw [show V = [τ.v0, τ.v1, τ.v2, τ.v3, e].toFinset by simp [V]]
        exact List.toFinset_card_of_nodup hdistinct
      have hσcard : σ.verts.toFinset.card ≤ 4 := by
        calc
          σ.verts.toFinset.card ≤ σ.verts.length := List.toFinset_card_le σ.verts
          _ = 4 := rfl
      have := Finset.card_le_card hVσ
      omega
  · rintro ⟨hFnonempty, hFV, hFproper⟩
    have hFV' : F ⊆ V := by simpa [V] using hFV
    have hssub : F ⊂ V := Finset.ssubset_iff_subset_ne.mpr ⟨hFV', by
      simpa [V] using hFproper⟩
    obtain ⟨x, hxV, hxF⟩ := (Finset.ssubset_iff_of_subset hFV').mp hssub
    have hxCases : x = τ.v0 ∨ x = τ.v1 ∨ x = τ.v2 ∨ x = τ.v3 ∨ x = e := by
      simpa [V] using hxV
    apply (mem_triangulationPreAbstractComplex_iff K F).mpr
    refine ⟨hFnonempty, ?_⟩
    have hmissing (z : Nat) (hzF : z ∉ F) : F ⊆ V.erase z := by
      intro y hy
      exact Finset.mem_erase.mpr ⟨fun hyz => hzF (hyz ▸ hy), hFV' hy⟩
    have hmiss := hmissing x hxF
    rcases hxCases with rfl | rfl | rfl | rfl | rfl
    · refine ⟨ρ123, h123K, ?_⟩
      rw [h123Finset]
      intro y hy
      have := hmiss hy
      simp only [Finset.mem_erase, Finset.mem_insert, Finset.mem_singleton] at this ⊢
      aesop
    · refine ⟨ρ023, h023K, ?_⟩
      rw [h023Finset]
      intro y hy
      have := hmiss hy
      simp only [Finset.mem_erase, Finset.mem_insert, Finset.mem_singleton] at this ⊢
      aesop
    · refine ⟨ρ013, h013K, ?_⟩
      rw [h013Finset]
      intro y hy
      have := hmiss hy
      simp only [Finset.mem_erase, Finset.mem_insert, Finset.mem_singleton] at this ⊢
      aesop
    · refine ⟨ρ012, h012K, ?_⟩
      rw [h012Finset]
      intro y hy
      have := hmiss hy
      simp only [Finset.mem_erase, Finset.mem_insert, Finset.mem_singleton] at this ⊢
      aesop
    · refine ⟨τ, hτK, ?_⟩
      rw [hτFinset]
      intro y hy
      have := hmiss hy
      simp only [Finset.mem_erase, Finset.mem_insert, Finset.mem_singleton] at this ⊢
      aesop

/-- The nonempty boundary complex on five (not necessarily distinct) named vertices. -/
def fourSimplexBoundaryPreAbstractComplex (a b c d e : Nat) :
    PreAbstractSimplicialComplex Nat where
  faces := {F | F.Nonempty ∧ F ⊆ {a, b, c, d, e} ∧ F ≠ {a, b, c, d, e}}
  isRelLowerSet_faces := by
    intro F hF
    refine ⟨hF.1, ?_⟩
    intro G hGF hG
    refine ⟨hG, hGF.trans hF.2.1, ?_⟩
    intro hGV
    apply hF.2.2
    apply Finset.Subset.antisymm hF.2.1
    intro x hx
    apply hGF
    simpa [hGV] using hx

theorem mem_fourSimplexBoundaryPreAbstractComplex_iff
    (a b c d e : Nat) (F : Finset Nat) :
    F ∈ fourSimplexBoundaryPreAbstractComplex a b c d e ↔
      F.Nonempty ∧ F ⊆ {a, b, c, d, e} ∧ F ≠ {a, b, c, d, e} :=
  Iff.rfl

/-- The generated pre-abstract complex is the explicitly named boundary complex from the
five-vertex certificate. -/
theorem ClosedTriangulationCore.exists_triangulationPreAbstractComplex_eq_fourSimplexBoundary
    {K : Triangulation}
    (hcore : ClosedTriangulationCore K)
    (hPhi : PhiSupport K = 0)
    (hconn : TetrahedronVertexOverlapConnected K)
    {τ : Tet}
    (hτK : τ ∈ K.tets)
    (hτ : τ.verts.Nodup) :
    ∃ e,
      [τ.v0, τ.v1, τ.v2, τ.v3, e].Nodup ∧
      triangulationPreAbstractComplex K =
        fourSimplexBoundaryPreAbstractComplex τ.v0 τ.v1 τ.v2 τ.v3 e := by
  obtain ⟨e, hdistinct, hmem⟩ :=
    hcore.triangulationPreAbstractComplex_mem_iff_fourSimplexBoundary hPhi hconn hτK hτ
  refine ⟨e, hdistinct, ?_⟩
  ext F
  exact hmem F

end Poincare
