import Mathlib.Analysis.Convex.GaugeRescale
import Mathlib.Analysis.Convex.Topology
import Mathlib.Analysis.Normed.Affine.AddTorsorBases
import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
import Mathlib.Geometry.Euclidean.Simplex
import Mathlib.Topology.Homeomorph.Lemmas
import Mathlib.Topology.Category.TopCat.Sphere

open Set

namespace Poincare

/--
The ambient Euclidean three-space used for the geometric tetrahedron.
-/
abbrev TetrahedronAmbient :=
  EuclideanSpace ℝ (Fin 3)

/--
A noncomputably chosen affine basis of Euclidean three-space indexed by four
vertices.

Its four points are affinely independent and their affine span is the whole
ambient space.
-/
noncomputable def tetrahedronAffineBasis :
    AffineBasis (Fin 4) ℝ TetrahedronAmbient := by

  exact
    Classical.choice
      (AffineBasis.exists_affineBasis_of_finiteDimensional
        (ι := Fin 4)
        (k := ℝ)
        (V := TetrahedronAmbient)
        (P := TetrahedronAmbient)
        (by simp))

/--
The three-dimensional simplex determined by `tetrahedronAffineBasis`.
-/
noncomputable def tetrahedronSimplex :
    Affine.Simplex ℝ TetrahedronAmbient 3 where

  points :=
    tetrahedronAffineBasis

  independent :=
    tetrahedronAffineBasis.ind

/--
The closed convex tetrahedral body generated by the four affine-basis points.
-/
noncomputable def tetrahedronBody :
    Set TetrahedronAmbient :=
  convexHull ℝ
    (Set.range tetrahedronAffineBasis)

theorem tetrahedronBody_convex :
    Convex ℝ tetrahedronBody := by

  exact
    convex_convexHull ℝ _

theorem tetrahedronAffineBasis_full_span :
    affineSpan ℝ
        (Set.range tetrahedronAffineBasis) =
      ⊤ := by

  exact
    tetrahedronAffineBasis.tot

theorem tetrahedronBody_interior_nonempty :
    (interior tetrahedronBody).Nonempty := by

  refine
    ⟨Finset.univ.centroid
        ℝ tetrahedronAffineBasis,
      ?_⟩

  simpa [
    tetrahedronBody
  ] using
    tetrahedronAffineBasis.centroid_mem_interior_convexHull

theorem tetrahedronBody_isCompact :
    IsCompact tetrahedronBody := by

  simpa [
    tetrahedronBody
  ] using
    (Set.finite_range
        tetrahedronAffineBasis).isCompact_convexHull ℝ

theorem tetrahedronBody_isBounded :
    Bornology.IsBounded tetrahedronBody := by

  exact
    tetrahedronBody_isCompact.isBounded

/--
The frontier of the full-dimensional tetrahedral body is homeomorphic to the
unit sphere in Euclidean three-space.

This is a genuine topological statement about the frontier subtype.
-/
noncomputable def tetrahedronFrontierHomeomorphUnitSphere :
    ↥(frontier tetrahedronBody) ≃ₜ
      ↥(Metric.sphere
        (0 : TetrahedronAmbient)
        1) := by

  let hex :
      ∃ h : TetrahedronAmbient ≃ₜ TetrahedronAmbient,
        h '' interior tetrahedronBody =
            Metric.ball 0 1 ∧
        h '' closure tetrahedronBody =
            Metric.closedBall 0 1 ∧
        h '' frontier tetrahedronBody =
            Metric.sphere 0 1 :=
    exists_homeomorph_image_interior_closure_frontier_eq_unitBall
      tetrahedronBody_convex
      tetrahedronBody_interior_nonempty
      tetrahedronBody_isBounded

  let h :
      TetrahedronAmbient ≃ₜ
        TetrahedronAmbient :=
    Classical.choose hex

  have hspec :
      h '' interior tetrahedronBody =
          Metric.ball 0 1 ∧
      h '' closure tetrahedronBody =
          Metric.closedBall 0 1 ∧
      h '' frontier tetrahedronBody =
          Metric.sphere 0 1 := by

    exact
      Classical.choose_spec hex

  exact
    (h.image
        (frontier tetrahedronBody)).trans
      (Homeomorph.setCongr
        hspec.2.2)

theorem tetrahedronSimplex_points_eq_affineBasis :
    tetrahedronSimplex.points =
      tetrahedronAffineBasis := by

  rfl

end Poincare
