import Mathlib.Analysis.Convex.GaugeRescale
import Mathlib.Analysis.Convex.Combination
import Mathlib.Analysis.Convex.Topology
import Mathlib.Analysis.Normed.Affine.AddTorsorBases
import Mathlib.LinearAlgebra.AffineSpace.FiniteDimensional
import Mathlib.Geometry.Euclidean.Simplex
import Mathlib.Topology.Homeomorph.Lemmas
import Mathlib.Topology.Category.TopCat.Sphere

open Set

namespace Poincare

/--
The ambient Euclidean three-space used for the geometric tetrahedron.
-/
abbrev TetrahedronAmbient :=
  EuclideanSpace ℝ (Fin 3)

/--
A noncomputably chosen affine basis of Euclidean three-space indexed by four
vertices.

Its four points are affinely independent and their affine span is the whole
ambient space.
-/
noncomputable def tetrahedronAffineBasis :
    AffineBasis (Fin 4) ℝ TetrahedronAmbient := by

  exact
    Classical.choice
      (AffineBasis.exists_affineBasis_of_finiteDimensional
        (ι := Fin 4)
        (k := ℝ)
        (V := TetrahedronAmbient)
        (P := TetrahedronAmbient)
        (by simp))

/--
The three-dimensional simplex determined by `tetrahedronAffineBasis`.
-/
noncomputable def tetrahedronSimplex :
    Affine.Simplex ℝ TetrahedronAmbient 3 where

  points :=
    tetrahedronAffineBasis

  independent :=
    tetrahedronAffineBasis.ind

/--
The closed convex tetrahedral body generated by the four affine-basis points.
-/
noncomputable def tetrahedronBody :
    Set TetrahedronAmbient :=
  convexHull ℝ
    (Set.range tetrahedronAffineBasis)

theorem tetrahedronBody_convex :
    Convex ℝ tetrahedronBody := by

  exact
    convex_convexHull ℝ _

theorem tetrahedronAffineBasis_full_span :
    affineSpan ℝ
        (Set.range tetrahedronAffineBasis) =
      ⊤ := by

  exact
    tetrahedronAffineBasis.tot

theorem tetrahedronBody_interior_nonempty :
    (interior tetrahedronBody).Nonempty := by

  refine
    ⟨Finset.univ.centroid
        ℝ tetrahedronAffineBasis,
      ?_⟩

  simpa [
    tetrahedronBody
  ] using
    tetrahedronAffineBasis.centroid_mem_interior_convexHull

theorem tetrahedronBody_isCompact :
    IsCompact tetrahedronBody := by

  simpa [
    tetrahedronBody
  ] using
    (Set.finite_range
        tetrahedronAffineBasis).isCompact_convexHull ℝ

theorem tetrahedronBody_isBounded :
    Bornology.IsBounded tetrahedronBody := by

  exact
    tetrahedronBody_isCompact.isBounded

/--
The frontier of the full-dimensional tetrahedral body is homeomorphic to the
unit sphere in Euclidean three-space.

This is a genuine topological statement about the frontier subtype.
-/
noncomputable def tetrahedronFrontierHomeomorphUnitSphere :
    ↥(frontier tetrahedronBody) ≃ₜ
      ↥(Metric.sphere
        (0 : TetrahedronAmbient)
        1) := by

  let hex :
      ∃ h : TetrahedronAmbient ≃ₜ TetrahedronAmbient,
        h '' interior tetrahedronBody =
            Metric.ball 0 1 ∧
        h '' closure tetrahedronBody =
            Metric.closedBall 0 1 ∧
        h '' frontier tetrahedronBody =
            Metric.sphere 0 1 :=
    exists_homeomorph_image_interior_closure_frontier_eq_unitBall
      tetrahedronBody_convex
      tetrahedronBody_interior_nonempty
      tetrahedronBody_isBounded

  let h :
      TetrahedronAmbient ≃ₜ
        TetrahedronAmbient :=
    Classical.choose hex

  have hspec :
      h '' interior tetrahedronBody =
          Metric.ball 0 1 ∧
      h '' closure tetrahedronBody =
          Metric.closedBall 0 1 ∧
      h '' frontier tetrahedronBody =
          Metric.sphere 0 1 := by

    exact
      Classical.choose_spec hex

  exact
    (h.image
        (frontier tetrahedronBody)).trans
      (Homeomorph.setCongr
        hspec.2.2)

theorem tetrahedronSimplex_points_eq_affineBasis :
    tetrahedronSimplex.points =
      tetrahedronAffineBasis := by

  rfl


/--
The geometric face opposite `i : Fin 4` has exactly the three tetrahedral
vertices whose labels lie in `Finset.univ.erase i`.
-/
theorem tetrahedronFaceOpposite_vertexSet_eq_image_erase
    (i : Fin 4) :
    Set.range
        (tetrahedronSimplex.faceOpposite i).points =
      tetrahedronSimplex.points ''
        (↑(Finset.univ.erase i) : Set (Fin 4)) := by

  rw [
    Affine.Simplex.range_faceOpposite_points
  ]

  congr 1

  ext j

  simp

/--
The frontier of the tetrahedral body is exactly the union of its four filled
facets.
-/
theorem tetrahedronFrontier_eq_facetUnion :
    frontier tetrahedronBody =
      {p | ∃ i : Fin 4,
        p ∈ convexHull ℝ
          (Set.range (tetrahedronSimplex.faceOpposite i).points)} := by
  rw [tetrahedronBody_isCompact.isClosed.frontier_eq]
  ext p
  rw [mem_diff, mem_setOf_eq]
  rw [tetrahedronBody, tetrahedronAffineBasis.interior_convexHull,
    tetrahedronAffineBasis.convexHull_eq_nonneg_coord]
  constructor
  · rintro ⟨hpnonneg, hpnotpos⟩
    change ¬ ∀ i, 0 < tetrahedronAffineBasis.coord i p at hpnotpos
    rw [not_forall] at hpnotpos
    simp only [not_lt] at hpnotpos
    obtain ⟨i, hi⟩ := hpnotpos
    have hizero : tetrahedronAffineBasis.coord i p = 0 :=
      le_antisymm hi (hpnonneg i)
    refine ⟨i, ?_⟩
    let w : Fin 4 → ℝ := fun j => tetrahedronAffineBasis.coord j p
    have hsum : ∑ j, w j = 1 :=
      tetrahedronAffineBasis.sum_coord_apply_eq_one p
    have hsum_erase : ∑ j ∈ Finset.univ.erase i, w j = 1 := by
      rw [Finset.sum_erase]
      · simpa [w, hizero] using hsum
      · exact hizero
    have hface : ∀ j ∈ Finset.univ.erase i,
        tetrahedronSimplex.points j ∈
          Set.range (tetrahedronSimplex.faceOpposite i).points := by
      intro j hj
      rw [Affine.Simplex.range_faceOpposite_points]
      exact ⟨j, by simpa using hj, rfl⟩
    have hmem := Finset.centerMass_mem_convexHull
      (s := Set.range (tetrahedronSimplex.faceOpposite i).points)
      (z := tetrahedronSimplex.points)
      (Finset.univ.erase i) (fun j _ => hpnonneg j)
      (hsum_erase.symm ▸ zero_lt_one) hface
    rw [← affineCombination_eq_centerMass hsum_erase] at hmem
    have heq : (Finset.univ.erase i).affineCombination ℝ
        tetrahedronSimplex.points w = p := by
      rw [Finset.affineCombination_eq_weightedVSubOfPoint_vadd_of_sum_eq_one
        (Finset.univ.erase i) w tetrahedronSimplex.points hsum_erase
        (tetrahedronSimplex.points i)]
      rw [← tetrahedronAffineBasis.affineCombination_coord_eq_self p]
      simp only [tetrahedronSimplex_points_eq_affineBasis]
      rw [Finset.affineCombination_eq_weightedVSubOfPoint_vadd_of_sum_eq_one
        Finset.univ w tetrahedronAffineBasis hsum (tetrahedronAffineBasis i)]
      simp [w]
    rwa [heq] at hmem
  · rintro ⟨i, hpface⟩
    have hsubset :
        convexHull ℝ (Set.range (tetrahedronSimplex.faceOpposite i).points) ⊆
          convexHull ℝ (Set.range tetrahedronAffineBasis) := by
      apply convexHull_mono
      rw [Affine.Simplex.range_faceOpposite_points,
        tetrahedronSimplex_points_eq_affineBasis]
      exact Set.image_subset_range _ _
    have hpbodymem : p ∈ convexHull ℝ (Set.range tetrahedronAffineBasis) :=
      hsubset hpface
    have hpbody : ∀ j, 0 ≤ tetrahedronAffineBasis.coord j p := by
      rwa [tetrahedronAffineBasis.convexHull_eq_nonneg_coord] at hpbodymem
    refine ⟨hpbody, ?_⟩
    intro hpinterior
    have hpaff : p ∈ affineSpan ℝ
        (Set.range (tetrahedronSimplex.faceOpposite i).points) :=
      (convexHull_min (subset_affineSpan ℝ _) (affineSpan ℝ _).convex) hpface
    have hsum := tetrahedronAffineBasis.sum_coord_apply_eq_one p
    have hizero : tetrahedronAffineBasis.coord i p = 0 := by
      have := (Affine.Simplex.affineCombination_mem_affineSpan_faceOpposite_iff
        (s := tetrahedronSimplex) (i := i) hsum).mp ?_
      · simpa [tetrahedronSimplex_points_eq_affineBasis] using this
      · simpa [tetrahedronSimplex_points_eq_affineBasis,
          tetrahedronAffineBasis.affineCombination_coord_eq_self p] using hpaff
    have hipos := hpinterior i
    rw [hizero] at hipos
    exact (lt_irrefl 0) hipos

end Poincare
