import Mathlib.AlgebraicTopology.SimplicialComplex.Basic
import Poincare.Triangulation

namespace Poincare

/-- The pre-abstract simplicial complex generated by the tetrahedra of a triangulation. -/
def triangulationPreAbstractComplex (K : Triangulation) :
    PreAbstractSimplicialComplex Nat where
  faces := {F | F.Nonempty ∧ ∃ τ : Tet, τ ∈ K.tets ∧ F ⊆ τ.verts.toFinset}
  isRelLowerSet_faces := by
    intro F hF
    refine ⟨hF.1, ?_⟩
    intro G hGF hG
    obtain ⟨τ, hτ, hFτ⟩ := hF.2
    exact ⟨hG, τ, hτ, hGF.trans hFτ⟩

theorem mem_triangulationPreAbstractComplex_iff (K : Triangulation) (F : Finset Nat) :
    F ∈ (triangulationPreAbstractComplex K).faces ↔
      F.Nonempty ∧
      ∃ τ : Tet, τ ∈ K.tets ∧ F ⊆ τ.verts.toFinset :=
  Iff.rfl

end Poincare
