import Verifier.KernelLocalization
import Mathlib.LinearAlgebra.quotient
import Mathlib.LinearAlgebra.LinearIndependent

namespace Verifier

open Submodule

variable {α : Type*}

/-- Cycle space placeholder (F₂ edge space). -/
abbrev CycleSpace (α : Type*) := α →₀ ZMod 2

/-- Local span generated by radius-R balls (abstract placeholder). -/
def localSpan (Δ R : ℕ) : Submodule (ZMod 2) (CycleSpace α) :=
  ⊤  -- replaced later with actual span of local cycles

/-- Quotient cycle space. -/
def quotientCycleSpace (Δ R : ℕ) :=
  (CycleSpace α) ⧸ (localSpan (α:=α) Δ R)

/-- Quotient projection. -/
def π (Δ R : ℕ) :
  CycleSpace α →ₗ[ZMod 2] quotientCycleSpace (α:=α) Δ R :=
  Submodule.mkQ _

/-- Bridge lemma. -/
theorem quotient_zero_iff (Δ R : ℕ) (x : CycleSpace α) :
  π (α:=α) Δ R x = 0 ↔ x ∈ localSpan (α:=α) Δ R :=
by
  exact Submodule.quotient_eq_zero_iff_mem

/-- Disjoint support ⇒ linear independence in quotient. -/
theorem disjoint_support_indep_quotient
  (Δ R : ℕ)
  (qs : Finset (CycleSpace α))
  (hdisj : ∀ q₁≠q₂ ∈ qs, Disjoint q₁.support q₂.support)
  (hnz : ∀ q ∈ qs, π (α:=α) Δ R q ≠ 0) :
  LinearIndependent (ZMod 2) (fun q => π (α:=α) Δ R q) := by
  classical
  intro l hl
  have hsum : ∑ q in qs, l q • π (α:=α) Δ R q = 0 := hl
  have hpre :
    π (α:=α) Δ R (∑ q in qs, l q • q) = 0 := by
    simpa using hsum
  have hmem :
    (∑ q in qs, l q • q) ∈ localSpan (α:=α) Δ R :=
    (quotient_zero_iff (α:=α) Δ R _).mp hpre

  have hcoeff :
    ∀ q ∈ qs, l q = 0 := by
    intro q hq
    by_contra hneq
    have hnonzero : q ≠ 0 := by
      intro h0
      have := hnz q hq
      simpa [h0] using this
    obtain ⟨e, he⟩ := by
      have : q.support.Nonempty := by
        simpa using Finsupp.support_nonempty_iff.mpr hnonzero
      exact this
    have := congrArg (fun f => f e) hsum
    simp at this
    contradiction

  ext q
  by_cases hq : q ∈ qs <;> simp [hq, hcoeff]

/-- Dimension lower bound via independent family. -/
theorem quotient_dim_lower
  (Δ R : ℕ)
  (qs : Finset (CycleSpace α))
  (hdisj : ∀ q₁≠q₂ ∈ qs, Disjoint q₁.support q₂.support)
  (hnz : ∀ q ∈ qs, π (α:=α) Δ R q ≠ 0) :
  Module.rank (ZMod 2) (quotientCycleSpace (α:=α) Δ R)
    ≥ qs.card := by
  classical
  have hindep :=
    disjoint_support_indep_quotient (α:=α) Δ R qs hdisj hnz
  exact Module.rank_ge_of_linearIndependent _ hindep

end Verifier
