import Regge.Regge
import Poincare.Triangulation
import Poincare.TriangulationPreAbstractComplex
import Poincare.TriangulationGeometricComplex
import Poincare.TriangulationTopologicalGeometricComplex
import Poincare.TriangulationTopologicalGeometricCarrier
import Poincare.TriangulationTopologicalSimplyConnected
import Poincare.TriangulationTopologicalS3
import Poincare.TriangulationTopologicalGeometricDecomposition
import Poincare.TriangulationTopologicalGeometricIntersections
import Poincare.TriangulationTopologicalVertexLink
import Poincare.TriangulationTopologicalVertexLinkRealizationChange
import Poincare.Moves
import Poincare.Descent
import Poincare.Recognition
import Poincare.LocalDelta
import Poincare.LocalSphericalDescent
import Poincare.PhiZeroCharacterizesS3
import Poincare.NormalizationImpliesS3
import Poincare.SolveStepBuild
import Poincare.MoveSemanticsBuild

import Poincare.ZeroDefect
import Poincare.VertexLink
import Poincare.VertexLinkConnectednessCounterexample
import Poincare.VertexLinkLocalConnectednessCounterexample

import Poincare.TetrahedronSphere

import Poincare.VertexLinkTetrahedronBridge
