import Regge.Regge
import Poincare.Triangulation
import Poincare.Moves
import Poincare.Descent
import Poincare.Recognition
import Poincare.LocalDelta
import Poincare.LocalSphericalDescent
import Poincare.PhiZeroCharacterizesS3
import Poincare.NormalizationImpliesS3
import Poincare.SolveStepBuild
import Poincare.MoveSemanticsBuild

import Poincare.ZeroDefect
import Poincare.VertexLink
import Poincare.VertexLinkConnectednessCounterexample
import Poincare.VertexLinkLocalConnectednessCounterexample

import Poincare.TetrahedronSphere
